# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(887, 758)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 40, 201, 301))
        self.tableView.setObjectName("tableView")
        self.tableView_2 = QtWidgets.QTableView(self.centralwidget)
        self.tableView_2.setGeometry(QtCore.QRect(220, 40, 201, 301))
        self.tableView_2.setObjectName("tableView_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 10, 131, 17))
        self.label.setObjectName("label")
        self.tableView_3 = QtWidgets.QTableView(self.centralwidget)
        self.tableView_3.setGeometry(QtCore.QRect(10, 380, 201, 301))
        self.tableView_3.setObjectName("tableView_3")
        self.tableView_4 = QtWidgets.QTableView(self.centralwidget)
        self.tableView_4.setGeometry(QtCore.QRect(220, 380, 201, 301))
        self.tableView_4.setObjectName("tableView_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 350, 131, 17))
        self.label_2.setObjectName("label_2")
        self.tableView_5 = QtWidgets.QTableView(self.centralwidget)
        self.tableView_5.setGeometry(QtCore.QRect(450, 40, 201, 301))
        self.tableView_5.setObjectName("tableView_5")
        self.tableView_6 = QtWidgets.QTableView(self.centralwidget)
        self.tableView_6.setGeometry(QtCore.QRect(660, 40, 201, 301))
        self.tableView_6.setObjectName("tableView_6")
        self.tableView_7 = QtWidgets.QTableView(self.centralwidget)
        self.tableView_7.setGeometry(QtCore.QRect(660, 380, 201, 301))
        self.tableView_7.setObjectName("tableView_7")
        self.tableView_8 = QtWidgets.QTableView(self.centralwidget)
        self.tableView_8.setGeometry(QtCore.QRect(450, 380, 201, 301))
        self.tableView_8.setObjectName("tableView_8")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 20, 131, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 20, 131, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(480, 20, 131, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(700, 20, 131, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(690, 360, 131, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(230, 360, 131, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(470, 360, 131, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(40, 360, 131, 17))
        self.label_10.setObjectName("label_10")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 887, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "+VE 2 -VE"))
        self.label_2.setText(_translate("MainWindow", "-VE 2 +VE"))
        self.label_3.setText(_translate("MainWindow", "3 min"))
        self.label_4.setText(_translate("MainWindow", "15 min"))
        self.label_5.setText(_translate("MainWindow", "30 min"))
        self.label_6.setText(_translate("MainWindow", "1 Hours"))
        self.label_7.setText(_translate("MainWindow", "1 Hours"))
        self.label_8.setText(_translate("MainWindow", "15 min"))
        self.label_9.setText(_translate("MainWindow", "30 min"))
        self.label_10.setText(_translate("MainWindow", "3 min"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
